apiVersion: v1
kind: Pod
metadata:
  name: environment-demo
  namespace: roboshop
spec:
  containers:
    - name: nginx
      image: nginx:latest
      env:
        - name: ENV
          value: dev
        - name: project
          value: roboshop
        - name: platform
          value: kubernetes